In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [4]:
arr = np.array([1, 2, 3])
arr, arr.dtype

(array([1, 2, 3]), dtype('int64'))

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
r = range(10)
np.array(r)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
numar = 2 ** 63
numar

9223372036854775808

In [9]:
np.array([numar])

array([9223372036854775808], dtype=uint64)

In [12]:
-128, 127 # -2**7 -> 2 ** 7 - 1
0, 255    # 0 -> 2 ** 8 - 1

(0, 255)

In [ ]:
array = np.array([-1, numar])
array.dtype

dtype('float64')

In [ ]:
array = np.array([-1, numar - 1 ])
array.dtype

dtype('int64')

In [16]:
array = np.array([10, 20, 5, 6, 99, 123, -13, 400, 30, 1, 20, 3])
array


array([ 10,  20,   5,   6,  99, 123, -13, 400,  30,   1,  20,   3])

In [17]:
array.sum()

np.int64(704)

In [18]:
sum(array)

np.int64(704)

In [19]:
array.max(), array.min()

(np.int64(400), np.int64(-13))

In [20]:
print(array.max(), array.min())

400 -13


In [21]:
array.argmax(), array.argmin()

(np.int64(7), np.int64(6))

In [22]:
print(array.argmax(), array.argmin())

7 6


In [23]:
array

array([ 10,  20,   5,   6,  99, 123, -13, 400,  30,   1,  20,   3])

In [24]:
print(array)

[ 10  20   5   6  99 123 -13 400  30   1  20   3]


In [25]:
array * 2

array([ 20,  40,  10,  12, 198, 246, -26, 800,  60,   2,  40,   6])

In [26]:
array

array([ 10,  20,   5,   6,  99, 123, -13, 400,  30,   1,  20,   3])

In [27]:
array = array * 3
array

array([  30,   60,   15,   18,  297,  369,  -39, 1200,   90,    3,   60,
          9])

In [37]:
array -= 10
array

array([ -70,  -40,  -85,  -82,  197,  269, -139, 1100,  -10,  -97,  -40,
        -91])

In [38]:
array + array

array([-140,  -80, -170, -164,  394,  538, -278, 2200,  -20, -194,  -80,
       -182])

In [39]:
array[ array > 0 ]

array([ 197,  269, 1100])

In [40]:
array

array([ -70,  -40,  -85,  -82,  197,  269, -139, 1100,  -10,  -97,  -40,
        -91])

In [ ]:
array [0]

np.int64(-70)

In [42]:
array[0:2]

array([-70, -40])

In [43]:
array > 0

array([False, False, False, False,  True,  True, False,  True, False,
       False, False, False])