In [2]:
import numpy as np

# Creaţi un program care va genera aleatoriu 5 numere şi care la ieşire va genera un array în care fiecare element este mapat la True sau False dacă numărul este par sau respectiv impar.

In [8]:
np.random.randint(1, 100)

64

In [14]:
array = np.random.randint(1, 100, 5)
array

array([82, 21, 97,  1, 84])

In [15]:
array[0]

np.int64(82)

In [17]:
print(array[0] % 2 == 0)

True


In [18]:
array % 2 == 0

array([ True, False, False, False,  True])

In [20]:
lista = [82, 21, 97,  1, 84]


In [21]:
array[ array % 2 == 0 ]

array([82, 84])

In [22]:
conditie = array % 2 == 0

array[ conditie ]

array([82, 84])

In [25]:
conditie_pare = array % 2 == 0

array_pare = array[ conditie_pare ]
array_pare

array([82, 84])

In [26]:
conditie_impare = array % 2 != 0

array_impare = array[ conditie_impare ]
array_impare

array([21, 97,  1])

In [27]:
list(array_pare)

[np.int64(82), np.int64(84)]

In [30]:
print(list(array_impare)[0])

21


In [32]:
x = 10
type(x)

int

In [33]:
float(x)

10.0

In [40]:
x = np.int64(x)
x

np.int64(10)

In [41]:
x / 2

np.float64(5.0)

In [42]:
x ** 2

np.int64(100)

In [44]:
x * np.float64(1.19)

np.float64(11.899999999999999)

# De această dată verificați dacă numărele generate sunt pare, impare și/sau divizibile cu 3. Adăugați-le în trei liste (pare, impare, divizibile cu 3). Comparați lungimea celor 3 liste.

In [45]:
array = np.random.randint(1, 100, 10)
array

array([13, 82, 99, 55, 67, 45, 71, 40, 22, 10])

In [47]:
pare = array[array % 2 == 0]
impare = array[array % 2 == 1]
divizibile_cu_3 = array[array % 3 == 0]

In [48]:
pare, impare, divizibile_cu_3

(array([82, 40, 22, 10]), array([13, 99, 55, 67, 45, 71]), array([99, 45]))

In [53]:
impare_divizibile_cu_3 = array[(array % 2 == 1) & (array % 3 == 0)]
impare_divizibile_cu_3

array([99, 45])

In [55]:
conditia_impare = array % 2 == 1
conditia_div_3 = array % 3 == 0

impare_divizibile_cu_3 = array[conditia_impare & conditia_div_3]
impare_divizibile_cu_3

array([99, 45])